org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# --- FIX JAVA 26 ERROR ---
# Si experimentas el error java.lang.IllegalArgumentException: 26 al compilar, 
# descomenta la siguiente línea y pon la ruta a tu instalación de Java 17 o Java 21:
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
# -------------------------
