// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYVDQx2ki7ugY22sRWrD55S7cH2lMdcIs',
    appId: '1:178817144351:android:30a93990e68784f32ee72a',
    messagingSenderId: '178817144351',
    projectId: 'sistema-gestion-servicio-4c747',
    storageBucket: 'sistema-gestion-servicio-4c747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBKBkeOD7WhxAT_U5VxEk9sKS3ooj98Y',
    appId: '1:178817144351:ios:476b0d1fe920c2fa2ee72a',
    messagingSenderId: '178817144351',
    projectId: 'sistema-gestion-servicio-4c747',
    storageBucket: 'sistema-gestion-servicio-4c747.firebasestorage.app',
    iosClientId:
        '178817144351-h3l7mlji4bepcuseps6vb0p0s8if4917.apps.googleusercontent.com',
    iosBundleId: 'com.jvaldez.flowserv',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYVDQx2ki7ugY22sRWrD55S7cH2lMdcIs',
    appId:
        '1:178817144351:web:30a93990e68784f32ee72a', // Usando el mismo ID base de Android para el placeholder
    messagingSenderId: '178817144351',
    projectId: 'sistema-gestion-servicio-4c747',
    authDomain: 'sistema-gestion-servicio-4c747.firebaseapp.com',
    storageBucket: 'sistema-gestion-servicio-4c747.firebasestorage.app',
  );
}
